# Generated by Django 3.2.8 on 2021-11-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_auto_20211103_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='identity',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hero',
            name='strength',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hero',
            name='weakness',
            field=models.TextField(default=''),
        ),
    ]
