# Generated by Django 3.2.8 on 2021-11-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='identity',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='hero',
            name='strength',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='hero',
            name='weakness',
            field=models.TextField(default=' '),
        ),
    ]
